= Pact Consumer

include::./includes/attributes.adoc[]

This extension ensures Pact consumer libraries works well with Quarkus applications, including with continuous testing.
It is based on version {pact-version} of the Pact JVM JUnit 5 library.

== Installation

To use this extension, add the `io.quarkiverse:quarkus-pact-consumer` extension first to your build file.
Choose a 1.x version for Quarkus 3, and a 0.x version for Quarkus 2.

== Installation

To use this extension, add the `io.quarkiverse:quarkus-pact-provider` extension first to your build file.
Choose a 1.x version for Quarkus 3, and a 0.x version for Quarkus 2.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse</groupId>
    <artifactId>quarkus-pact-consumer</artifactId>
    <version>{project-version}</version>
    <scope>provided</scope>
</dependency>
----

Note the `provided` scope, rather than `test` or default. This is needed for the tests to pass in continuous testing mode.

== Example usage

Use Pact as you https://docs.pact.io/implementation_guides/jvm/provider/junit5[normally would].
Remember that your consumer tests should be testing your application's code, not the behaviour of the Pact-provided mock.

For example, a simple consumer test for REST endpoints would look like this:

[source,java]
----
include::{examples-dir}/consumer/ConsumerTest.java[tag=include]
----

<1> Add `@Consumer` annotations to the class, along with metadata about who the consumer is, and what provider is being used.
<2> Needed to enable dependency injection of the rest client.
<3> The consumer under test.
<4> We use the Pact DSL to define what the provider should return, given the request.
<5> Here we define our mock, which is also our expectations for the provider.
There is no need to verify these in this test; instead, the provider test will verify them.
<6> This test is realistic (in a simplified way) of how a consumer test might look.
<7> We have hardcoded the mock response, so the colour parameter we pass in is irrelevant (for this particular test) It tests how the consumer under test uses what the mock passes back, *not* the mock itself.

[[extension-configuration-reference]]
== Extension Configuration Reference

For the moment, Pact needs to be configured by the normal https://docs.pact.io/implementation_guides/jvm/docs/system-properties[Pact system properties].

== Known limitations

- If continuous testing is being used, the dependency scope cannot be `test`. The `provided` scope is a good alternative.
- `@TestProfile` does not work in dev mode (https://github.com/quarkiverse/quarkus-pact/issues/58[GitHub issue])
- A harmless `java.lang.NoClassDefFoundError: org/apache/hc/client5/http/fluent/Request` message will be produced if https://docs.pact.io/telemetry[Pact tracking] is enabled (https://github.com/quarkiverse/quarkus-pact/issues/57[GitHub issue])

include::./includes/resources.adoc[]

