= Pact Consumer

include::./includes/attributes.adoc[]

This extension ensures Pact consumer libraries works well with Quarkus applications, including with continuous testing.
It is based on version {pact-version} of the Pact JVM JUnit 5 library.

== Installation

To use this extension, add the `io.quarkiverse:quarkus-pact-consumer` extension first to your build file.
Choose a 1.x version for Quarkus 3, and a 0.x version for Quarkus 2.

== Installation

To use this extension, add the `io.quarkiverse:quarkus-pact-provider` extension first to your build file.
Choose a 1.x version for Quarkus 3, and a 0.x version for Quarkus 2.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse</groupId>
    <artifactId>quarkus-pact-consumer</artifactId>
    <version>{project-version}</version>
    <scope>test</scope>
</dependency>
----

== Example usage

Use Pact as you https://docs.pact.io/implementation_guides/jvm/provider/junit5[normally would].
Remember that your consumer tests should be testing your application's code, not the behaviour of the Pact-provided mock.

For example, a simple consumer test for REST endpoints would look like this:

[source,java]
----
include::{examples-dir}/consumer/ConsumerTest.java[tag=include]
----

<1> Add `@Consumer` annotations to the class, along with metadata about who the consumer is, and what provider is being used.
<2> The consumer under test.
<3> This defines what the body of the request could look like; we are generic and say it can be anything that meets the schema.
We could be stricter and put more expectations on what the consumer sends.
<4> We use the Pact DSL to define what the provider should return, given the request.
<5> Here we define our mock, which is also our expectations for the provider.
There is no need to verify these in this test; instead, the provider test will verify them.
<6> This test is realistic (in a simplified way) of how a consumer test might look.
<7> We have hardcoded the mock response, so the colour parameter we pass in is irrelevant (for this particular test) It tests how the consumer under test uses what the mock passes back, *not* the mock itself.

[[extension-configuration-reference]]
== Extension Configuration Reference

For the moment, Pact needs to be configured by the normal https://docs.pact.io/implementation_guides/jvm/docs/system-properties[Pact system properties].

== Known limitations

- Consumer tests cannot directly access the Pact `MockServer` when continuous testing is being used (https://github.com/quarkiverse/quarkus-pact/issues/73[GitHub issue])
- `@TestProfile` does not work in dev mode (https://github.com/quarkiverse/quarkus-pact/issues/58[GitHub issue])

include::./includes/resources.adoc[]

